In [3]:
import numpy as np
from pyDOE import *
from scipy.stats.distributions import norm

In [4]:
LOADS = [0,8,8,10,10,10,16,22,24,26,32,30,28,22,18,16,16,20,24,28,34,38,30,22,12]

In [171]:
### LATIN HYPERCUBE SAMPLING ###

In [176]:
### Test Example ###

np.random.seed(12)                                      #seed must be called before each operation for consistent results
s = 8                                                   #s is the center/mean of the distribution for fitting

lhd = lhs(1, samples=5)                                 #lhd is created
lhd_fit = norm(loc=s, scale=np.sqrt((1/3)*s)).ppf(lhd)  #lhd is fitted to new mean and std

print(lhd)
print('----------------')
print(lhd_fit)

[[0.70674788]
 [0.452663  ]
 [0.80291499]
 [0.03083257]
 [0.34800994]]
----------------
[[8.88819933]
 [7.80577821]
 [9.39143986]
 [4.9484324 ]
 [7.36199151]]


In [212]:
samples_vector = []
main_array = []
sample_size = 5

for number,i in enumerate(LOADS):
    if i == 0 :
        lhd = np.zeros(sample_size)          #scipy.norm cant handle 0 resulting in NaN, therefore we create array of zeros
        lhd = lhd.reshape(sample_size,1)
    else:
        np.random.seed(number)
        lhd = lhs(1, samples=sample_size)
        lhd = np.array(norm(loc=i, scale=np.sqrt((1/3)*i)).ppf(lhd)) 

    main_array.append(lhd)

main_array = np.array(main_array)

for i in range(len(main_array[0])):
    samples_vector.append(main_array[:,i])



In [213]:
samples_vector

[array([[ 0.        ],
        [ 7.5863826 ],
        [ 5.782057  ],
        [ 7.76222492],
        [12.83167392],
        [ 9.4141357 ],
        [13.87345575],
        [23.781553  ],
        [24.52652956],
        [24.45938024],
        [32.21898928],
        [33.78028573],
        [29.66166879],
        [20.15218243],
        [18.45752882],
        [17.0306727 ],
        [18.62484911],
        [18.69122558],
        [29.33836857],
        [31.38811334],
        [32.9675548 ],
        [41.55667066],
        [32.35560665],
        [18.58226482],
        [10.25892568]]),
 array([[ 0.        ],
        [ 8.67562915],
        [ 9.95240584],
        [13.69794813],
        [11.19131092],
        [12.31587132],
        [16.37352914],
        [29.09381598],
        [26.88988908],
        [25.99376196],
        [36.1799791 ],
        [32.08329759],
        [27.63664431],
        [28.88914607],
        [18.6307804 ],
        [15.47969011],
        [16.05870654],
        [19.59909409],
        [

In [19]:
def get_lhs_sample(sample_size = 1000,loads = LOADS):
    samples_vector = []
    main_array = []

    for number,i in enumerate(loads):
        if i == 0 :
            lhd = np.zeros(sample_size)      #scipy.norm cant handle 0 resulting in NaN, therefore we create array of zeros
            lhd = lhd.reshape(sample_size,1)
        else:
            np.random.seed(number)
            lhd = lhs(1, samples=sample_size)
            lhd = np.array(norm(loc=i, scale=np.sqrt((1/3)*i)).ppf(lhd)) 

        main_array.append(lhd)

    main_array = np.array(main_array)

    for i in range(len(main_array[0])):
        samples_vector.append(main_array[:,i])

    return samples_vector

In [20]:
test = get_lhs_sample(5,LOADS)
test

[array([[ 0.        ],
        [ 7.5863826 ],
        [ 5.782057  ],
        [ 7.76222492],
        [12.83167392],
        [ 9.4141357 ],
        [13.87345575],
        [23.781553  ],
        [24.52652956],
        [24.45938024],
        [32.21898928],
        [33.78028573],
        [29.66166879],
        [20.15218243],
        [18.45752882],
        [17.0306727 ],
        [18.62484911],
        [18.69122558],
        [29.33836857],
        [31.38811334],
        [32.9675548 ],
        [41.55667066],
        [32.35560665],
        [18.58226482],
        [10.25892568]]),
 array([[ 0.        ],
        [ 8.67562915],
        [ 9.95240584],
        [13.69794813],
        [11.19131092],
        [12.31587132],
        [16.37352914],
        [29.09381598],
        [26.88988908],
        [25.99376196],
        [36.1799791 ],
        [32.08329759],
        [27.63664431],
        [28.88914607],
        [18.6307804 ],
        [15.47969011],
        [16.05870654],
        [19.59909409],
        [

In [53]:
def get_av_samples(values:list, sample_size=1000, seed=12):
    # Set seed
    np.random.seed(seed)
    # Covariance matrix of values. Variance was given.
    cov_pl = np.diagflat(np.array(values)*1/3)
    # Calculate normal distribution for half of the sample size.
    normal_dis = np.random.multivariate_normal(values, cov_pl, size=int(sample_size/2))
    # Calculate athetics of these sample
    antithetics = np.array(values) - (normal_dis - np.array(values))
    # Concatenate both samples to one.
    samples = np.concatenate((normal_dis, antithetics))
    return samples

In [54]:
samples = get_av_samples(LOADS)

In [55]:
samples

array([[ 0.        ,  8.86113064,  9.04635852, ..., 32.38164676,
        24.9678632 ,  9.94093959],
       [ 0.        ,  2.86029034, 11.66087313, ..., 27.95264411,
        20.06686803, 12.63733058],
       [ 0.        ,  5.24400343, 10.29880981, ..., 33.16525893,
        21.77401849,  9.66748248],
       ...,
       [ 0.        ,  8.85600747,  8.11690661, ..., 26.04853352,
        26.62214792, 11.48516798],
       [ 0.        ,  8.51965576,  8.02948311, ..., 30.10904141,
        25.22350808, 15.70132754],
       [ 0.        ,  8.07258063,  5.44940208, ..., 29.09858273,
        20.76750823, 12.0158643 ]])

In [62]:
samples[499,:]

array([ 0.        ,  7.92741937, 10.55059792, 10.15307579,  8.73602338,
        5.50392051, 14.4132223 , 21.88102607, 24.30763912, 32.43111823,
       31.75242823, 32.55598258, 34.85781064, 20.33843349, 17.05565387,
       16.73980686, 20.52910177, 20.06670768, 21.00157531, 26.54547852,
       34.10656419, 30.82054604, 30.90141727, 23.23249177, 11.9841357 ])

In [61]:
samples[999, :]

array([ 0.        ,  8.07258063,  5.44940208,  9.84692421, 11.26397662,
       14.49607949, 17.5867777 , 22.11897393, 23.69236088, 19.56888177,
       32.24757177, 27.44401742, 21.14218936, 23.66156651, 18.94434613,
       15.26019314, 11.47089823, 19.93329232, 26.99842469, 29.45452148,
       33.89343581, 45.17945396, 29.09858273, 20.76750823, 12.0158643 ])